//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DefaultForColor1 {
            get {
                return ((int)(this["DefaultForColor1"]));
            }
            set {
                this["DefaultForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DefaultForColor2 {
            get {
                return ((int)(this["DefaultForColor2"]));
            }
            set {
                this["DefaultForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DefaultForColor3 {
            get {
                return ((int)(this["DefaultForColor3"]));
            }
            set {
                this["DefaultForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeatInFreezerForColor1 {
            get {
                return ((int)(this["MeatInFreezerForColor1"]));
            }
            set {
                this["MeatInFreezerForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeatInFreezerForColor2 {
            get {
                return ((int)(this["MeatInFreezerForColor2"]));
            }
            set {
                this["MeatInFreezerForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeatInFreezerForColor3 {
            get {
                return ((int)(this["MeatInFreezerForColor3"]));
            }
            set {
                this["MeatInFreezerForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeatInRefrigeratorForColor1 {
            get {
                return ((int)(this["MeatInRefrigeratorForColor1"]));
            }
            set {
                this["MeatInRefrigeratorForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeatInRefrigeratorForColor2 {
            get {
                return ((int)(this["MeatInRefrigeratorForColor2"]));
            }
            set {
                this["MeatInRefrigeratorForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeatInRefrigeratorForColor3 {
            get {
                return ((int)(this["MeatInRefrigeratorForColor3"]));
            }
            set {
                this["MeatInRefrigeratorForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColdCollationInFreezerForColor1 {
            get {
                return ((int)(this["ColdCollationInFreezerForColor1"]));
            }
            set {
                this["ColdCollationInFreezerForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColdCollationInFreezerForColor2 {
            get {
                return ((int)(this["ColdCollationInFreezerForColor2"]));
            }
            set {
                this["ColdCollationInFreezerForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColdCollationInFreezerForColor3 {
            get {
                return ((int)(this["ColdCollationInFreezerForColor3"]));
            }
            set {
                this["ColdCollationInFreezerForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColdCollationInRefrigeratorForColor1 {
            get {
                return ((int)(this["ColdCollationInRefrigeratorForColor1"]));
            }
            set {
                this["ColdCollationInRefrigeratorForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColdCollationInRefrigeratorForColor2 {
            get {
                return ((int)(this["ColdCollationInRefrigeratorForColor2"]));
            }
            set {
                this["ColdCollationInRefrigeratorForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColdCollationInRefrigeratorForColor3 {
            get {
                return ((int)(this["ColdCollationInRefrigeratorForColor3"]));
            }
            set {
                this["ColdCollationInRefrigeratorForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hús")]
        public string Meat {
            get {
                return ((string)(this["Meat"]));
            }
            set {
                this["Meat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Felvágott")]
        public string ColdCollation {
            get {
                return ((string)(this["ColdCollation"]));
            }
            set {
                this["ColdCollation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tejtermék")]
        public string Dairy {
            get {
                return ((string)(this["Dairy"]));
            }
            set {
                this["Dairy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tojás")]
        public string Egg {
            get {
                return ((string)(this["Egg"]));
            }
            set {
                this["Egg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Készétel")]
        public string Ready {
            get {
                return ((string)(this["Ready"]));
            }
            set {
                this["Ready"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tartós")]
        public string Conserve {
            get {
                return ((string)(this["Conserve"]));
            }
            set {
                this["Conserve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zölds, Gyüm")]
        public string VegsAndFruits {
            get {
                return ((string)(this["VegsAndFruits"]));
            }
            set {
                this["VegsAndFruits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mélyhutött")]
        public string DeepFrozen {
            get {
                return ((string)(this["DeepFrozen"]));
            }
            set {
                this["DeepFrozen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nasi")]
        public string Munchies {
            get {
                return ((string)(this["Munchies"]));
            }
            set {
                this["Munchies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Készétel")]
        public string Chemicals {
            get {
                return ((string)(this["Chemicals"]));
            }
            set {
                this["Chemicals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fagyasztó")]
        public string Freezer {
            get {
                return ((string)(this["Freezer"]));
            }
            set {
                this["Freezer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Huto")]
        public string Refrigerator {
            get {
                return ((string)(this["Refrigerator"]));
            }
            set {
                this["Refrigerator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lakás")]
        public string Flat {
            get {
                return ((string)(this["Flat"]));
            }
            set {
                this["Flat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DairyInFreezerForColor1 {
            get {
                return ((int)(this["DairyInFreezerForColor1"]));
            }
            set {
                this["DairyInFreezerForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DairyInFreezerForColor2 {
            get {
                return ((int)(this["DairyInFreezerForColor2"]));
            }
            set {
                this["DairyInFreezerForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DairyInFreezerForColor3 {
            get {
                return ((int)(this["DairyInFreezerForColor3"]));
            }
            set {
                this["DairyInFreezerForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DairyInRefrigeratorForColor1 {
            get {
                return ((int)(this["DairyInRefrigeratorForColor1"]));
            }
            set {
                this["DairyInRefrigeratorForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DairyInRefrigeratorForColor2 {
            get {
                return ((int)(this["DairyInRefrigeratorForColor2"]));
            }
            set {
                this["DairyInRefrigeratorForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DairyInRefrigeratorForColor3 {
            get {
                return ((int)(this["DairyInRefrigeratorForColor3"]));
            }
            set {
                this["DairyInRefrigeratorForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EggInRefrigeratorForColor1 {
            get {
                return ((int)(this["EggInRefrigeratorForColor1"]));
            }
            set {
                this["EggInRefrigeratorForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EggInRefrigeratorForColor2 {
            get {
                return ((int)(this["EggInRefrigeratorForColor2"]));
            }
            set {
                this["EggInRefrigeratorForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EggInRefrigeratorForColor3 {
            get {
                return ((int)(this["EggInRefrigeratorForColor3"]));
            }
            set {
                this["EggInRefrigeratorForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EggInFlatForColor1 {
            get {
                return ((int)(this["EggInFlatForColor1"]));
            }
            set {
                this["EggInFlatForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EggInFlatForColor2 {
            get {
                return ((int)(this["EggInFlatForColor2"]));
            }
            set {
                this["EggInFlatForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EggInFlatForColor3 {
            get {
                return ((int)(this["EggInFlatForColor3"]));
            }
            set {
                this["EggInFlatForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReadyInFreezerForColor1 {
            get {
                return ((int)(this["ReadyInFreezerForColor1"]));
            }
            set {
                this["ReadyInFreezerForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReadyInFreezerForColor2 {
            get {
                return ((int)(this["ReadyInFreezerForColor2"]));
            }
            set {
                this["ReadyInFreezerForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReadyInFreezerForColor3 {
            get {
                return ((int)(this["ReadyInFreezerForColor3"]));
            }
            set {
                this["ReadyInFreezerForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReadyInRefrigeratorForColor1 {
            get {
                return ((int)(this["ReadyInRefrigeratorForColor1"]));
            }
            set {
                this["ReadyInRefrigeratorForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReadyInRefrigeratorForColor2 {
            get {
                return ((int)(this["ReadyInRefrigeratorForColor2"]));
            }
            set {
                this["ReadyInRefrigeratorForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReadyInRefrigeratorForColor3 {
            get {
                return ((int)(this["ReadyInRefrigeratorForColor3"]));
            }
            set {
                this["ReadyInRefrigeratorForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConserveForColor1 {
            get {
                return ((int)(this["ConserveForColor1"]));
            }
            set {
                this["ConserveForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConserveForColor2 {
            get {
                return ((int)(this["ConserveForColor2"]));
            }
            set {
                this["ConserveForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConserveForColor3 {
            get {
                return ((int)(this["ConserveForColor3"]));
            }
            set {
                this["ConserveForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VegsAndFruitsInRefrigeratorForColor1 {
            get {
                return ((int)(this["VegsAndFruitsInRefrigeratorForColor1"]));
            }
            set {
                this["VegsAndFruitsInRefrigeratorForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VegsAndFruitsInRefrigeratorForColor2 {
            get {
                return ((int)(this["VegsAndFruitsInRefrigeratorForColor2"]));
            }
            set {
                this["VegsAndFruitsInRefrigeratorForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VegsAndFruitsInRefrigeratorForColor3 {
            get {
                return ((int)(this["VegsAndFruitsInRefrigeratorForColor3"]));
            }
            set {
                this["VegsAndFruitsInRefrigeratorForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VegsAndFruitsInFlatForColor1 {
            get {
                return ((int)(this["VegsAndFruitsInFlatForColor1"]));
            }
            set {
                this["VegsAndFruitsInFlatForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VegsAndFruitsInFlatForColor2 {
            get {
                return ((int)(this["VegsAndFruitsInFlatForColor2"]));
            }
            set {
                this["VegsAndFruitsInFlatForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VegsAndFruitsInFlatForColor3 {
            get {
                return ((int)(this["VegsAndFruitsInFlatForColor3"]));
            }
            set {
                this["VegsAndFruitsInFlatForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeepFrozenInFreezerForColor1 {
            get {
                return ((int)(this["DeepFrozenInFreezerForColor1"]));
            }
            set {
                this["DeepFrozenInFreezerForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeepFrozenInFreezerForColor2 {
            get {
                return ((int)(this["DeepFrozenInFreezerForColor2"]));
            }
            set {
                this["DeepFrozenInFreezerForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeepFrozenInFreezerForColor3 {
            get {
                return ((int)(this["DeepFrozenInFreezerForColor3"]));
            }
            set {
                this["DeepFrozenInFreezerForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeepFrozenInRefrigeratorForColor1 {
            get {
                return ((int)(this["DeepFrozenInRefrigeratorForColor1"]));
            }
            set {
                this["DeepFrozenInRefrigeratorForColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeepFrozenInRefrigeratorForColor2 {
            get {
                return ((int)(this["DeepFrozenInRefrigeratorForColor2"]));
            }
            set {
                this["DeepFrozenInRefrigeratorForColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeepFrozenInRefrigeratorForColor3 {
            get {
                return ((int)(this["DeepFrozenInRefrigeratorForColor3"]));
            }
            set {
                this["DeepFrozenInRefrigeratorForColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GmailUsernameOfSender {
            get {
                return ((string)(this["GmailUsernameOfSender"]));
            }
            set {
                this["GmailUsernameOfSender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GmailPasswordOfSender {
            get {
                return ((string)(this["GmailPasswordOfSender"]));
            }
            set {
                this["GmailPasswordOfSender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GmailUsernameOfReceiver {
            get {
                return ((string)(this["GmailUsernameOfReceiver"]));
            }
            set {
                this["GmailUsernameOfReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendOnMondays {
            get {
                return ((bool)(this["SendOnMondays"]));
            }
            set {
                this["SendOnMondays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendOnTuesdays {
            get {
                return ((bool)(this["SendOnTuesdays"]));
            }
            set {
                this["SendOnTuesdays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendOnWednesdays {
            get {
                return ((bool)(this["SendOnWednesdays"]));
            }
            set {
                this["SendOnWednesdays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendOnThursdays {
            get {
                return ((bool)(this["SendOnThursdays"]));
            }
            set {
                this["SendOnThursdays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendOnFridays {
            get {
                return ((bool)(this["SendOnFridays"]));
            }
            set {
                this["SendOnFridays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendOnSaturdays {
            get {
                return ((bool)(this["SendOnSaturdays"]));
            }
            set {
                this["SendOnSaturdays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendOnSundays {
            get {
                return ((bool)(this["SendOnSundays"]));
            }
            set {
                this["SendOnSundays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeAtMondays {
            get {
                return ((string)(this["TimeAtMondays"]));
            }
            set {
                this["TimeAtMondays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeAtTuesdays {
            get {
                return ((string)(this["TimeAtTuesdays"]));
            }
            set {
                this["TimeAtTuesdays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeAtWednesdays {
            get {
                return ((string)(this["TimeAtWednesdays"]));
            }
            set {
                this["TimeAtWednesdays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeAtThursdays {
            get {
                return ((string)(this["TimeAtThursdays"]));
            }
            set {
                this["TimeAtThursdays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeAtFridays {
            get {
                return ((string)(this["TimeAtFridays"]));
            }
            set {
                this["TimeAtFridays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeAtSaturdays {
            get {
                return ((string)(this["TimeAtSaturdays"]));
            }
            set {
                this["TimeAtSaturdays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeAtSundays {
            get {
                return ((string)(this["TimeAtSundays"]));
            }
            set {
                this["TimeAtSundays"] = value;
            }
        }
    }
}
